all:
	(cd nftSimple;  make -f Makefile)

clean:
	(cd nftSimple;  make -f Makefile clean)

allclean:
	(cd nftSimple;  make -f Makefile allclean)
	rm -f Makefile

distclean:
	(cd nftSimple;  make -f Makefile distclean)
	rm -f Makefile
